# Generated by Django 3.1.5 on 2021-01-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Men Fashion', 'Men Fashion'), ('Women Fashion', 'Women Fashion'), ('Gagets', 'Gagets'), ('Electronics', 'Electronics')], max_length=50)),
                ('Price', models.FloatField()),
                ('brand', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('image', models.FileField(upload_to='product/')),
            ],
        ),
    ]
