# Generated by Django 3.1.5 on 2021-01-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cart_cartproduct_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
