# Generated by Django 3.1.5 on 2021-01-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
