# Generated by Django 3.1.5 on 2021-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20210203_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Payment Failed', 'Payment Failed'), ('Order Confirm', 'Order Confirm'), ('Order received', 'Order received'), ('Order Processing', 'Order Processing'), ('Order On The Way', 'Order On The Way'), ('Order Conpleated', 'Order Conpleated'), ('Order Canceled', 'Order Canceled')], max_length=50),
        ),
    ]
